/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 09 20:30:38 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import ar.edu.unrc.game2048.GenerateCellStrategy;
import ar.edu.unrc.game2048.GenerateDeterministicCellStrategy;
import ar.edu.unrc.game2048.GenerateRandomCellStrategy;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.isLosingBoard();
      board0.moveUp();
      board1.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(331, 331);
      board_Position0.toString();
      int int0 = 3087;
      Board.Position board_Position1 = new Board.Position(331, 3087);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("(331, 331)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.(331, 331)
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Direction.values();
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = new Board(37, generateRandomCellStrategy0);
      board0.getScore();
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      board0.moveDown();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = new Board();
      generateRandomCellStrategy0.addTile(board0);
      board0.hasEmptyCells();
      board0.equals(generateRandomCellStrategy0);
      Cell cell0 = Cell.EMPTY;
      board0.setCell(0, 0, cell0);
      board0.getEmptyPositions();
      board0.moveRight();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(4, (-4341));
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      Board board0 = new Board();
      board0.equals((Object) null);
      board0.moveUp();
      board0.hashCode();
      board_Position0.toString();
      board0.isLosingBoard();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("(4, -4341)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.(4, -4341)
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveRight();
      board1.getScore();
      board0.equals((Object) null);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      int int0 = 122;
      Board.Position board_Position0 = new Board.Position(122, 122);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.equals((Object) null);
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = null;
      try {
        board0 = new Board(122);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Max Size Allowed is 64x64
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position((-1381), (-1381));
      board_Position0.equals((Object) null);
      Cell cell0 = Cell.EMPTY;
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      int int0 = (-2457);
      Board.Position board_Position0 = new Board.Position((-2457), (-2457));
      int[] intArray0 = new int[0];
      board_Position0.toString();
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      board_Position0.equals(generateDeterministicCellStrategy0);
      Board board0 = null;
      try {
        board0 = new Board(11, generateDeterministicCellStrategy0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("ar.edu.unrc.game2048.GenerateDeterministicCellStrategy", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board();
      board0.hasEmptyCells();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      int int0 = 0;
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(0, 0, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2760, (-863));
      board_Position0.equals("-f}c-;*sVX");
      Board board0 = new Board();
      int int0 = 0;
      // Undeclared exception!
      try { 
        board0.getCell(0, (-863));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, -863) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.moveUp();
      board0.toString();
      board0.hashCode();
      board0.isFull();
      board0.getEmptyPositions();
      board0.hashCode();
      board0.getScore();
      board0.toString();
      board0.moveDown();
      board0.moveDown();
      board0.hashCode();
      Object object0 = new Object();
      board0.equals(object0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      int int0 = 0;
      // Undeclared exception!
      try { 
        board0.getCell(0, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      int int0 = 64;
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = new Board(64, generateRandomCellStrategy0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.hashCode();
      board0.hashCode();
      board0.repOk();
      board0.getSize();
      Board.Direction.values();
      board0.moveRight();
      board0.repOk();
      Board.Position board_Position0 = new Board.Position(64, 2048);
      board0.moveRight();
      board_Position0.toString();
      board_Position0.toString();
      Board board1 = new Board();
      board0.toString();
      board1.moveLeft();
      board1.moveUp();
      board_Position0.equals(board1);
      board_Position0.toString();
      board1.toString();
      board1.getEmptyPositions();
      board1.moveRight();
      // Undeclared exception!
      try { 
        board0.getCell(2048, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      board0.repOk();
      board0.moveDown();
      board0.getCell(0, 0);
      board0.moveLeft();
      board0.moveDown();
      board0.moveLeft();
      board0.moveUp();
      board0.getCell(0, 0);
      board0.moveUp();
      board0.moveRight();
      board0.moveRight();
      board0.toString();
      // Undeclared exception!
      try { 
        board0.setCell(0, 2181, (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (0, 2181) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board();
      board0.toString();
      board0.moveUp();
      // Undeclared exception!
      try { 
        board0.getCell(593, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (593, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      int int0 = 64;
      Board board0 = new Board(64);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      int int0 = 1;
      Board board0 = null;
      try {
        board0 = new Board(1);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // 
         //
         verifyException("ar.edu.unrc.game2048.GenerateRandomCellStrategy", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board board0 = new Board();
      board0.getCell(1, 1);
      board0.moveUp();
      board0.hashCode();
      board0.getSize();
      board0.isFull();
      // Undeclared exception!
      try { 
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board.Direction.values();
      Board.Direction.values();
      int[] intArray0 = new int[0];
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      Board board0 = null;
      try {
        board0 = new Board(403, generateDeterministicCellStrategy0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Max Size Allowed is 64x64
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      board0.moveRight();
      board0.moveLeft();
      board0.moveUp();
      // Undeclared exception!
      try { 
        board0.getCell((-1227), (-1227));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1227, -1227) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      board0.repOk();
      board0.moveDown();
      board0.moveDown();
      // Undeclared exception!
      try { 
        board0.getCell((-263), (-263));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-263, -263) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board1.equals(board0);
      Object object0 = new Object();
      board1.equals(object0);
      board1.getScore();
      Board.Direction.values();
      board0.getSize();
      Board.Direction.values();
      Board.Position board_Position0 = new Board.Position(0, 0);
      Cell cell0 = Cell.EMPTY;
      board_Position0.equals(cell0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(4, (GenerateCellStrategy) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 4);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = null;
      try {
        board0 = new Board((-1411), generateRandomCellStrategy0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -1411
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board();
      int int0 = (-2376);
      int int1 = 1;
      // Undeclared exception!
      try { 
        board0.getCell(1, 5885);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 5885) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      board0.moveDown();
      Board board1 = new Board(board0);
      board1.repOk();
      board1.moveLeft();
      board1.getEmptyPositions();
      board1.isFull();
      board0.getSize();
      board0.isWinningBoard();
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.getCell(0, 0);
      board0.moveDown();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.toString();
      Board.Position board_Position0 = new Board.Position(0, 4);
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.isWinningBoard();
      board0.getEmptyPositions();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      int int0 = 4;
      int[] intArray0 = new int[4];
      intArray0[0] = 4;
      intArray0[1] = 168;
      intArray0[2] = 4;
      intArray0[3] = 4;
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      Board board0 = new Board(4, generateDeterministicCellStrategy0);
      generateDeterministicCellStrategy0.addTile(board0);
      // Undeclared exception!
      try { 
        board0.getCell(4, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (4, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      int int0 = 4;
      Board board0 = new Board(4);
      Board board1 = new Board(board0);
      Cell cell0 = Cell.EMPTY;
      // Undeclared exception!
      try { 
        board0.setCell(2048, (-1), cell0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, -1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(1, 1);
      board_Position0.toString();
      int[] intArray0 = new int[3];
      intArray0[0] = 1;
      intArray0[1] = (-2845);
      intArray0[2] = 1;
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      Board board0 = new Board(1, generateDeterministicCellStrategy0);
      Board board1 = new Board(board0);
      board1.isFull();
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      int[] intArray0 = new int[1];
      intArray0[0] = 34;
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      Board board0 = new Board(34, generateDeterministicCellStrategy0);
      board0.hashCode();
      // Undeclared exception!
      generateDeterministicCellStrategy0.addTile(board0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board();
      int int0 = (-1506);
      // Undeclared exception!
      try { 
        board0.getCell((-1506), (-1506));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1506, -1506) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = new Board();
      generateRandomCellStrategy0.addTile(board0);
      Board board1 = null;
      try {
        board1 = new Board(1, generateRandomCellStrategy0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // 
         //
         verifyException("ar.edu.unrc.game2048.GenerateRandomCellStrategy", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      board0.getCell(0, 0);
      board0.moveDown();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      board0.isWinningBoard();
      board0.toString();
      Board.Position board_Position0 = new Board.Position(0, 4);
      board_Position0.toString();
      board_Position0.equals(set0);
      board0.isWinningBoard();
      board0.getEmptyPositions();
      board0.moveDown();
      board0.moveUp();
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      int int0 = 327;
      Board board0 = null;
      try {
        board0 = new Board(327);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The Max Size Allowed is 64x64
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.moveRight();
      board0.moveRight();
      board0.moveUp();
      board0.repOk();
      board0.moveLeft();
      board0.moveDown();
      board0.moveDown();
      Object object0 = new Object();
      board0.repOk();
      board0.isLosingBoard();
      board0.moveUp();
      board0.getSize();
      board0.hashCode();
      Board.Position board_Position0 = new Board.Position(4, 2048);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.hashCode();
      board0.toString();
      board0.moveDown();
      board0.hasEmptyCells();
      board0.toString();
      board0.isWinningBoard();
      board0.getSize();
      board0.hasEmptyCells();
      board0.hasEmptyCells();
      board0.isFull();
      board0.moveDown();
      board0.moveLeft();
      Board.Direction.values();
      board0.getEmptyPositions();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board();
      board0.moveUp();
      board0.moveRight();
      board0.moveUp();
      board0.repOk();
      board0.moveLeft();
      board0.moveDown();
      board0.moveDown();
      Object object0 = new Object();
      board0.repOk();
      board0.isLosingBoard();
      board0.isLosingBoard();
      board0.equals(object0);
      board0.moveUp();
      board0.getSize();
      board0.hashCode();
      Board.Position board_Position0 = new Board.Position(4, 2048);
      board_Position0.toString();
      board_Position0.toString();
      board_Position0.toString();
      board0.hashCode();
      board_Position0.toString();
      board0.moveDown();
      board0.hasEmptyCells();
      board0.toString();
      board0.isWinningBoard();
      board0.getSize();
      board0.hasEmptyCells();
      board0.hasEmptyCells();
      board0.isFull();
      board0.moveDown();
      board0.moveLeft();
      Board.Direction.values();
      board0.moveUp();
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveDown();
      board1.isLosingBoard();
      board0.moveUp();
      board1.getEmptyPositions();
      Board.Position board_Position0 = new Board.Position(331, 331);
      board_Position0.toString();
      int int0 = 3087;
      Board.Position board_Position1 = new Board.Position(911, 3087);
      board_Position1.toString();
      board_Position0.equals(board_Position1);
      // Undeclared exception!
      try { 
        Board.Direction.valueOf("(331, 331)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No enum constant ar.edu.unrc.game2048.Board.Direction.(331, 331)
         //
         verifyException("java.lang.Enum", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      int int0 = 2;
      Board board0 = new Board(2);
      board0.moveLeft();
      Cell cell0 = new Cell(4);
      // Undeclared exception!
      try { 
        board0.getCell(2, 2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      int int0 = (-3466);
      int[] intArray0 = new int[4];
      intArray0[0] = 0;
      intArray0[1] = (-3466);
      intArray0[2] = (-3466);
      intArray0[3] = (-3466);
      GenerateDeterministicCellStrategy generateDeterministicCellStrategy0 = new GenerateDeterministicCellStrategy(intArray0);
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board board0 = null;
      try {
        board0 = new Board((-3466), generateRandomCellStrategy0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: -3466
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, (-1816));
      Board board0 = new Board();
      board0.repOk();
      board0.moveDown();
      board0.toString();
      board0.moveRight();
      board0.moveRight();
      board0.moveRight();
      board0.moveDown();
      board0.getSize();
      board0.moveLeft();
      board0.isWinningBoard();
      Board.Direction board_Direction0 = Board.Direction.RIGHT;
      board0.hashCode();
      Board.Direction.values();
      board0.isFull();
      board0.getScore();
      board0.getScore();
      board0.repOk();
      assertEquals(8, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      GenerateRandomCellStrategy generateRandomCellStrategy0 = new GenerateRandomCellStrategy();
      Board.Position board_Position0 = new Board.Position((-1887), (-2444));
      String string0 = board_Position0.toString();
      assertEquals("(-1887, -2444)", string0);
  }
}
